global:
  storageClass: "gp2"

redis:
  fullnameOverride: redis
  auth:
    enabled: false
  usePassword: false
  configmap: |-
    appendonly no

kafka:
  controller:
   replicaCount: 0
  kraft:
    enabled: false
  zookeeper:
    enabled: true
  broker:
    replicaCount: 1
    persistence:
      enabled: true
      size: 8Gi 
      storageClass: "gp2"
    extraConfig: |
      auto.create.topics.enable=true
      delete.topic.enable=true
      log.retention.hours=168
      log.retention.bytes=1073741824
      offsets.topic.replication.factor=1
      transaction.state.log.min.isr=1
      transaction.state.log.replication.factor=1
      default.replication.factor=1
      min.insync.replicas=1

    resources:
      requests:
        memory: 1Gi
      limits:
        memory: 2Gi

zookeeper:
  enabled: true
  replicaCount: 1
  persistence:
    enabled: true
    size: 8Gi
  volumePermissions:
    enabled: true
  extraConfig: |
    tickTime=2000
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi