global:
  storageClass: "gp2"

redis:
  fullnameOverride: redis
  auth:
    enabled: false
  usePassword: false
  configmap: |-
    appendonly no

kafka:
  controller:
   replicaCount: 0
  kraft:
    enabled: false
  zookeeper:
    enabled: true
  broker:
    replicaCount: 1
    persistence:
      enabled: true
      size: 8Gi 
      storageClass: "gp2"
    extraConfig: |
      offsets.topic.replication.factor=1
      transaction.state.log.min.isr=1
      transaction.state.log.replication.factor=1
      default.replication.factor=1
      min.insync.replicas=1
      listeners=INTERNAL://:9094,EXTERNAL://:9092
      advertised.listeners=INTERNAL://common-kafka-broker-0.common-kafka-broker-headless.default.svc.cluster.local:9094,EXTERNAL://common-kafka-broker-0.common-kafka-broker-headless.default.svc.cluster.local:9092
      listener.security.protocol.map=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      inter.broker.listener.name=INTERNAL

    resources:
      requests:
        memory: 1Gi
      limits:
        memory: 2Gi

zookeeper:
  enabled: true
  replicaCount: 1
  persistence:
    enabled: true
    size: 8Gi
  volumePermissions:
    enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi