apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  TICKETING_USER_URL: {{ .Values.secret.service.user | b64enc }}
  TICKETING_TICKETING_URL: {{ .Values.secret.service.ticketing | b64enc }}
  TICKETING_EVENT_URL: {{ .Values.secret.service.event | b64enc }}
  GATEWAY_URL: {{ .Values.secret.service.gateway | b64enc }}
  JWT_SECRET_KEY : {{ .Values.secret.jwt.key | b64enc }}
  JWT_ALGORITHM : {{ .Values.secret.jwt.algorithm | b64enc }}
  REDIS_HOST: {{ .Values.secret.redis.host | b64enc}}
  REDIS_PORT: {{ .Values.secret.redis.port | toString | b64enc}}