apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    {{- include "event.labels" . | nindent 4 }}
    job: ticketing
    app: ticketing
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "event.selectorLabels" . | nindent 4 }}
    app: ticketing
