apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  SERVER_BASE_URL: {{ .Values.secret.server.url | b64enc }}
  WEBSOCKET_SERVER_URL: {{ .Values.secret.websocket.server_url | b64enc }}