apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ticketing-service-monitor
  namespace: monitoring
  labels:
    release: prometheus
    app: prometheus
spec:
  jobLabel: job
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
  selector:
    matchLabels:
      app: ticketing
  # namespaceSelector:
  #   matchNames:
  #     - your-app-namespace
