loki:
  enabled: true

promtail:
  enabled: true

grafana:
  enabled: true
  service:
    # type: NodePort
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    hosts:
      - host: "grafana.gmmt.store"
    rules:
        paths:
          - path: /
            pathType: Prefix
            # backend:
            #   service:
            #     name: grafana-server
            #     port:
            #       number: 80

    tls: []