apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  # Kafka 설정
  KAFKA_BROKER_URL: {{ .Values.kafka.broker.url | toString }}
  KAFKA_TOPIC: {{ .Values.kafka.topic }}
  KAFKA_GROUP_ID: {{ .Values.kafka.groupId }}