argo-cd:
  server:
    service:
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts: 
        - "argocd.gmmt.store"
      rules:
        - host: "argocd.gmmt.store"
          http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: argocd-server
                    port:
                      number: 80
  
  redis:
    enabled: true
  
  dex:
    enabled: false