argo-cd:
  server:
    service:
      type: ClusterIP
    ingress:
      enabled: true
      hosts:
        - host: argocd.gmmt.sotre
          paths:
            - path: /
              pathType: Prefix