name: deploy all + install nginx

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
        
      - name: Deploy to EKS
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add argo https://argoproj.github.io/argo-helm
          helm repo update

          aws eks update-kubeconfig --name karpenter-cls

      # - name: Install NGINX Ingress Controller
      #   run: |
      #     if ! helm list -n ingress-nginx | grep -q ingress-nginx; then
      #       helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
      #       helm repo update
      #       helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
      #         --namespace ingress-nginx --create-namespace
      #     fi

      - name: Deploy Helm Charts
        run: |
          pushd charts/common
          helm dependency build
          popd

          pushd charts/argocd
          helm dependency build
          popd
          
          helm upgrade --install common ./charts/common

          helm upgrade --install argocd ./charts/argocd -n argocd --create-namespace
          
          for service in gateway fe user websocket event ticket-reservation-consumer ticketing; do
            pushd charts/$service
            helm dependency build
            popd

            helm upgrade --install ${service} ./charts/$service \
              -f ./charts/${service}/values.yaml
            
            kubectl rollout restart deployment ${service}
          done