name: Update Image Tag

on:
  repository_dispatch:
    types: [update-image]

jobs:
  update-value:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      
      - name: Update Values File
        run: |
          REPO_NAME="${{ github.event.client_payload.repo }}"
          SHA="${{ github.event.client_payload.sha }}"
          
          yq e '.image.tag = "'$SHA'"' -i charts/$REPO_NAME/values.yaml
          
      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "feat: update ${{ github.event.client_payload.repo }} image tag"
          git push